language: php

dist: trusty
group: deprecated-2017Q4


matrix:
  include:
  - os: linux
    sudo: required
    php:
      - nightly
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
    allow_failures:
        - php: nightly
  - os: linux
    sudo: required
    php:
      - 7.2
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - os: linux
    sudo: required
    php:
      - 7.1
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - os: linux
    sudo: required
    php:
      - 7.0
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - os: linux
    sudo: required
    php:
      - 5.6
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - os: linux
    sudo: required
    php:
      - 5.4
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - os: linux
    sudo: required
    php:
      - hhvm-3.18
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
    allow_failures:
        - php: hhvm-3.18
  - os: linux
    sudo: required
    php:
      - hhvm-nightly
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
    allow_failures:
        - php: hhvm-nightly
  - os: linux
    dist: precise
    sudo: required
    php:
      - 5.3
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    allow_failures:
        - php: 5.3
  - os: linux
    dist: precise
    sudo: required
    php:
      - 5.2
    services:
      - mysql
    before_script:
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    allow_failures:
        - php: 5.2
